### ISSUE TITLE
Crash dump handler needs /usr/bin/wget

### ISSUE THREAD

**Issue by mzabaluev** [flathub/org.electronjs.Electron2.BaseApp#13]
The crash dump handler built into Electron requires `/usr/bin/wget` to operate. Here's the relevant [source](https://github.com/electron/electron/blob/v7.2.4/shell/common/crash_reporter/linux/crash_dump_handler.cc#L350) for version 7.2.4, which is used by Visual Studio Code 1.45.1.

**Comment by mzabaluev** [comment]
As I understand it, the hardcoded location means the binary has to be provided by the runtime or its extensions.

**Comment by mzabaluev** [comment]
Filed an issue for the runtime: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1055

**Comment by fabianhauser** [comment]
This should be resolved with https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2705 .

**Comment by bbhtt** [comment]
I don't see any references to `wget` in Electron's current source. And `wget` exists in the currently supported runtimes 

22.08 https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/d8632183948d7c5b2b29f4fc7954b13d5df81353/elements/platform.bst#L82

23.08 https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/82ccd27bb92aa3934f8c2ff62bbe46ae4af7adf4/elements/platform.bst#L82

So this should be good to close. Please ping if something is broken.
