### ISSUE TITLE
Application name replaced by `app` for process list

### ISSUE THREAD

**Issue by RalfJung** [flathub/org.electronjs.Electron2.BaseApp#37]
When an electron application is started via this wrapper, it seems that it will always show up as `app` in process lists (I looked at `htop`). That is unfortunate because it makes it basically impossible to tell which application is actually hogging the CPU once there are two or more flatpak'd electron applications running.

Would be nice if there was some way to preserve the process name.

**Comment by refi64** [comment]
I'm pretty sure this is a bug in your process monitor that's using the `/app` path prefix, or in the specific application or its packaging. On my system, I can definitely observe all the usual process names inside `ps -A`'s output and in GNOME System Monitor.

**Comment by RalfJung** [comment]
Ah fair, I also see the right names in the KDE process manager. This might be an `htop` quirk. Thanks!
