### ISSUE TITLE
22.08 update is causing some users to crash

### ISSUE THREAD

**Issue by Pobega** [flathub/org.electronjs.Electron2.BaseApp#39]
I have a few users complaining about running into an error with loading an Electron application;

```FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.```

It seems related to the 22.08 upgrade. Is there anything I can do about this? Is there a way to disable hardware acceleration via a command line switch?

Edit: Seems like it might not be related directly to Electron: in https://github.com/flathub/com.fightcade.Fightcade/pull/112 I downgraded from 22.08 to 21.08 but affected users are still getting the error message. I could close this and move it somewhere else, but I'd like to know where this source error might be coming from?

**Comment by refi64** [comment]
It's probably not an issue with this repo specifically, but either way, some more logs are definitely needed :sweat_smile: there's a very large number of things that can go wrong with the GPU process.

**Comment by Pobega** [comment]
I ended up working around the issue by defaulting to turning off the GPU sandbox. It's not an ideal solution, but it works around the problem for Nvidia users (and the Electron application isn't the primary use-case, it's just a frontend to the games so I'm fine with the tradeoff.)

I don't own an Nvidia machine and got all of my information from users in a Discord so I cannot provide more context/logs, sorry.
