### ISSUE TITLE
--filesystem=/tmp necessary for app.requestSingleInstanceLock() to work

### ISSUE THREAD

**Issue by jonathon-love** [flathub/org.electronjs.Electron2.BaseApp#4]
hi,

i just wanted to record somewhere publicly that access to `/tmp` is necessary for the [`app.requestSingleInstanceLock()`](https://electronjs.org/docs/api/app#apprequestsingleinstancelock) to work (which most electron applications will want to use).

```
    "finish-args":[
        ...
        --filesystem=/tmp
    ],
```

**Comment by TingPing** [comment]
Just to expand on that if you want to report this upstream, I would suggest `$XDG_RUNTIME_DIR/app/$APP_ID/` as the directory to write such files (assuming electron apps have a unique app identifier).

**Comment by jonathon-love** [comment]
cool. thanks.

i've raised this issue [here](https://github.com/electron/electron/issues/15304).

(but i suspect it will be low/no-priority)

with thanks

**Comment by TingPing** [comment]
@jonathon-love I don't know why I didn't think of it before but how does adding `--env=TMPDIR=/var/tmp` to your finish args work?

**Comment by jonathon-love** [comment]
i think i tried this, but i'll try again.

**Comment by jonathon-love** [comment]
by golly it works!

**Comment by Erick555** [comment]
It's worth noting here that setting `TMPDIR` via `--env=TMPDIR` won't work for systems where bubbewrap is installed as setuid binary: https://github.com/flatpak/flatpak/issues/2641

Setting `TMPDIR` in wrapper which will run inside sandbox like:
```
export TMPDIR=/var/tmp"
exec APP "$@"
```
is more reliable.

**Comment by TingPing** [comment]
I'm not sure that makes sense, `bwrap --setenv=` exists entirely to bypass the suid problem.

EDIT: Apparently flatpak didn't use that? Anyway its a simple fix there.

**Comment by Erick555** [comment]
> EDIT: Apparently flatpak didn't use that? Anyway its a simple fix there.

yes, currently flatpak doesn't treat `TMPDIR` specially like it does for [LD_LIBRARY_PATH](https://github.com/flatpak/flatpak/blob/39903eab40920dab749a795ce2bef8ce54aacc1a/common/flatpak-run.c#L1319). We need a volunteer to submit patch...

**Comment by TingPing** [comment]
Thanks for the pointer, submitted =)

**Comment by Erick555** [comment]
Nice. This issue mostly affects debian so they may pick up this patch in just few years 😄 .
