### ISSUE TITLE
reCAPTCHA issues

### ISSUE THREAD

**Issue by Pobega** [flathub/org.electronjs.Electron2.BaseApp#41]
Hello,

I have reports of some users running into a problem with reCAPTCHA. I maintain [Fightcade](https://github.com/flathub/com.fightcade.Fightcade) which is an Electron frontend to playing arcade games with netplay. I am not a developer of Fightcade, just the maintainer of the Flatpak so I'm not personally familiar with what would or wouldn't trip reCAPTCHA.

I'm curious if it's possibly being tripped because the version of Chromium is out of date (I'm not sure if it's up to the baseapp/zypak to provide the Chromium binary or does that come bundled with the application?) Users have been working around the issue by launching the non-sandboxed version (gotten from Fightcade's website) to register/login then switching to the Flatpak to actually play games.

Any thoughts would be appreciated since I'm at a complete loss on this one.

**Comment by Erick555** [comment]
> (I'm not sure if it's up to the baseapp/zypak to provide the Chromium binary or does that come bundled with the application?

Electron/Chromium comes bundled with the application so this is wrong place.

**Comment by Pobega** [comment]
Noted, then maybe it's something else tripping reCAPTCHA. Perhaps something with the networking?

Anyway, I'll close this issue since it is unrelated to this repo, thanks.
