### ISSUE TITLE
FreeDesktop 23.08

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/org.electronjs.Electron2.BaseApp#43]
FreeDesktop 23.08 is out, and 21.08 is EOL. May a maintainer please create the branch for it?

I am considering this a blocker for [LunarClient](https://github.com/flathub/com.lunarclient.LunarClient/pull/32), do tell me if it is not.

**Comment by Erick555** [comment]
FreeDesktop 22.08 is still supported for another year, there is no immediate reason for switch.

**Comment by Etaash-mathamsetty** [comment]
> FreeDesktop 22.08 is still supported for another year, there is no immediate reason for switch.

? there are multiple branches, we just create a new branch for 23.08
won't effect any existing software on 22.08 and if there's interest from electron apps to switch to 23.08, they can

**Comment by Erick555** [comment]
Above I said there is no immediate reason for **apps** to switch to the new runtime. Clearly they shouldn't switch without baseapp making new branch for 23.08 first but I see they [did anyway](https://github.com/flathub/com.lunarclient.LunarClient/pull/32) which is obviously wrong.

**Comment by der-eismann** [comment]
@TingPing can you create a new 23.08 branch here?

**Comment by hfiguiere** [comment]
pushed. Give it a few hours.

**Comment by Doomsdayrs** [comment]
> pushed. Give it a few hours.

Can the default branch be changed to `23.08` as well?

**Comment by hfiguiere** [comment]
I don't have that kind of permissions.
