### ISSUE TITLE
Zypak issue

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.electronjs.Electron2.BaseApp#44]
This is a bit strange but there seems to an issue with using the Zypak build in the baseapp. I'm not sure why though.

Just building it again within the app seems to solve a failure to start as per https://github.com/flathub/com.nordpass.NordPass/pull/148

**Comment by bbhtt** [comment]
One of the issues there, is the app trying to use ptrace but not having the permission:

```
[0404/204710.672068:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
```

I don't know if that causes the crash. 

It could be that the baseapp needs a rebuild against latest freedesktop-sdk. However, a rebuild of baseapp will fail until flatpak-builder-lint can read `flathub.json` and allows skipping appstream checks for baseapps. Until that is fixed, not much can be done.

**Comment by bbhtt** [comment]
I triggered rebuilds of both branches, they should be published in 5-6 hours if nothing happens. Please rebuild the app against it and check if it fixes said issue.

https://buildbot.flathub.org/#/builders/6/builds/84085
https://buildbot.flathub.org/#/builders/6/builds/84087

If that doesn't work please build the app locally with zypak and debuginfo and try to generate a backtrace. Then report it to https://github.com/refi64/zypak

**Comment by RangHo** [comment]
As mentioned above, coming from downstream `com.discordapp.Discord`. I was noted that the issue I am having is an error from `zypak`, and I just confirmed that the same issue happens to any flatpaks based on this one.

Symptom is, any flatpak based on this platform fails to launch with the message:

```
[00 preload-host-spawn-strategy] Failed to call Spawn: org.freedesktop.DBus.Error.InvalidArgs: Could not find requesting pid
```

...where `00` is any arbitrary integer.

Could this be related to this issue here? If not, I'll proceed and create a new issue. Thanks!

**Comment by bbhtt** [comment]
I doubt it is related, considering the fixed it by including zypak in the app which is exactly the same version included in the baseapp and nothing changed between them

**Comment by RangHo** [comment]
Ah, thanks for the clarification 👍

Please disregard my question, then.

**Comment by bbhtt** [comment]
Zypak was updated two days ago on 23.08 branch please test it to see if there are any issues. Right now there's not much actionable here, so I'm closing this.
