### ISSUE TITLE
ambiguous name; outdated docs

### ISSUE THREAD

**Issue by fatmalama** [flathub/org.electronjs.Electron2.BaseApp#8]
it's not clear that this is just an environment for properly running an electron app _where you'd provide the electron and nodejs in your own manifest_
and it's not clear whether it'd work with newer versions of electron

I deduced the former from reading [this](http://docs.flatpak.org/en/latest/electron.html) which is for the old io.atom.* base app even tho it's on latest/

**Comment by TingPing** [comment]
This should be moved to https://github.com/flatpak/flatpak-docs

The demo is old so it references old things.

**Comment by fatmalama** [comment]
the docs part but the naming issue should go here

I propose `org.electronjs.BaseApp` :^)

**Comment by TingPing** [comment]
So what happens when Electron X comes out that has different dependencies?

Honestly the naming is fine, the purpose of the baseapp is just not super clear which is a documentation problem.

**Comment by fatmalama** [comment]
> So what happens when Electron X comes out that has different dependencies?

a new branch is added to the base app

e.g.
branch: '19.08+e2' for electron 2,

let's say electron 8 comes out this year and needs updated dependencies
branch: '19.08+e8'
then electron 9 comes out and doesn't need update, so the branch stays put
then fdo 20.08 comes out.
branch: '20.08+e8'

no '20.08+e2' as if they're sticking to an old electron runtime then they probably don't care to update to a new fdo runtime

think about it

**Comment by TingPing** [comment]
I suppose that is fine. I don't personally have time to deal with this though.
